#
# Circle CI 2.0 Docs
# 
# For info, see: https://circleci.com/docs/2.0/
#

# This file contains all the builds for devops 
# when something changes everything is rebuild and pushed.
# Not ideal but hell ...

version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
    working_directory: ~/wiki
    steps:
      - checkout

      - run: 
          name: Install required Packages
          command: |
            apk add --update bash ruby ruby-dev ruby-rdoc ruby-irb ruby-io-console make gcc g++ libffi libffi-dev nodejs
            gem install bundler
            bundle install

      - deploy:
          name: Deploy to GitHub Pages
          command: |
              git config --global user.email "$GITHUB_EMAIL" > /dev/null 2>&1
              git config --global user.name "$GITHUB_USERNAME" > /dev/null 2>&1
              ./deploy.sh
